#!/usr/bin/env python3
"""Refresh the AI & Automation section of the profile README.

Lists public repos for the GitHub user, filters for automation/AI/n8n repos by
topic OR name pattern, and rewrites the content between the
<!-- AI-AUTOMATIONS:START --> and <!-- AI-AUTOMATIONS:END --> markers.

Run locally: GH_TOKEN=$(gh auth token) python3 .github/scripts/refresh_automations.py
In CI: invoked by .github/workflows/refresh-automations.yml with GITHUB_TOKEN.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

USER = "artenisalija"
README = Path(__file__).resolve().parents[2] / "README.md"
MARKER_START = "<!-- AI-AUTOMATIONS:START -->"
MARKER_END = "<!-- AI-AUTOMATIONS:END -->"
AUTO_COMMENT = (
    "<!-- This block is auto-generated by "
    ".github/workflows/refresh-automations.yml — do not edit by hand. -->"
)

NAME_PATTERN = re.compile(r"(n8n|automation|autoposter|workflow)", re.IGNORECASE)
DETECT_TOPICS = {"n8n", "automation", "ai-automation", "workflow-automation", "ai"}


def gh_api(path: str) -> list | dict:
    """Call the GitHub API via the gh CLI, which uses GH_TOKEN automatically."""
    out = subprocess.check_output(["gh", "api", path], text=True)
    return json.loads(out)


def is_automation(repo: dict) -> bool:
    if repo.get("private") or repo.get("archived") or repo.get("fork"):
        return False
    if repo["name"].lower() == USER.lower():
        return False  # exclude the profile repo
    topics = set(repo.get("topics", []))
    if topics & DETECT_TOPICS:
        return True
    if NAME_PATTERN.search(repo["name"]):
        return True
    return False


def fetch_repos() -> list[dict]:
    repos: list[dict] = []
    page = 1
    while True:
        batch = gh_api(f"users/{USER}/repos?per_page=100&page={page}&sort=updated")
        if not isinstance(batch, list) or not batch:
            break
        repos.extend(batch)
        if len(batch) < 100:
            break
        page += 1
    return repos


def render(repos: list[dict]) -> str:
    if not repos:
        return "_No public automation repositories yet._"
    rows = ["| Automation | What it does |", "|---|---|"]
    for r in sorted(repos, key=lambda x: x["name"].lower()):
        desc = (r.get("description") or "").strip() or "—"
        desc = " ".join(desc.split()).replace("|", "\\|")
        rows.append(f"| **[{r['name']}]({r['html_url']})** | {desc} |")
    return "\n".join(rows)


def main() -> None:
    repos = [r for r in fetch_repos() if is_automation(r)]
    body = render(repos)
    new_block = f"{MARKER_START}\n{AUTO_COMMENT}\n\n{body}\n{MARKER_END}"

    text = README.read_text(encoding="utf-8")
    pattern = re.compile(
        re.escape(MARKER_START) + r".*?" + re.escape(MARKER_END),
        flags=re.DOTALL,
    )
    if not pattern.search(text):
        sys.exit(
            f"Markers not found in {README}. Add them between the intro and "
            "the Projects section before running this script."
        )
    new_text = pattern.sub(new_block, text)
    if new_text == text:
        print(f"No changes ({len(repos)} automation repos detected).")
        return
    README.write_text(new_text, encoding="utf-8")
    print(f"Updated README with {len(repos)} automation repos.")


if __name__ == "__main__":
    main()
